"""
This type stub file was generated by pyright.
"""

def parse_cookies_str(cookies):  # -> dict[Any, Any]:
    """
    parse cookies str to dict
    :param cookies: cookies str
    :type cookies: str
    :return: cookie dict
    :rtype: dict
    """
    ...

def file2dict(path):  # -> Any:
    ...

def grep_comma(num_str): ...
def str2num(num_str, convert_type=...):  # -> float | int:
    ...
