"""
This type stub file was generated by pyright.
"""

def use(broker, host, port=..., **kwargs):  # -> RemoteClient:
    ...

class RemoteClient:
    def __init__(self, broker, host, port=..., **kwargs) -> None: ...
    def prepare(
        self,
        config_path=...,
        user=...,
        password=...,
        exe_path=...,
        comm_password=...,
        **kwargs
    ):  # -> Any:
        """
        登陆客户端
        :param config_path: 登陆配置文件，跟参数登陆方式二选一
        :param user: 账号
        :param password: 明文密码
        :param exe_path: 客户端路径类似 r'C:\\htzqzyb2\\xiadan.exe',
            默认 r'C:\\htzqzyb2\\xiadan.exe'
        :param comm_password: 通讯密码
        :return:
        """
        ...

    @property
    def balance(self):  # -> Any:
        ...

    @property
    def position(self):  # -> Any:
        ...

    @property
    def today_entrusts(self):  # -> Any:
        ...

    @property
    def today_trades(self):  # -> Any:
        ...

    @property
    def cancel_entrusts(self):  # -> Any:
        ...

    def auto_ipo(self):  # -> Any:
        ...

    def exit(self):  # -> Any:
        ...

    def common_get(self, endpoint):  # -> Any:
        ...

    def buy(self, security, price, amount, **kwargs):  # -> Any:
        ...

    def sell(self, security, price, amount, **kwargs):  # -> Any:
        ...

    def cancel_entrust(self, entrust_no):  # -> Any:
        ...
